import type { Metadata } from "next";
// import { Montserrat } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import Center from "@/components/Center";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

// const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "PNGKY | welcome to my home🖐️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-my-white dark:bg-my-black",
          GeistSans.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Center>
            <Wrapper>
              <Navbar />
              {children}
            </Wrapper>
          </Center>
        </ThemeProvider>
      </body>
    </html>
  );
}
