import type { Metadata } from "next";
// import { Montserrat } from "next/font/google";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/utils/utility";
import Center from "@/components/Center";
import Wrapper from "@/components/Wrapper";
import Navbar from "@/components/Navbar";

// const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(GeistSans.className)}>
        <Center>
          <Wrapper>
            <Navbar />
            {children}
          </Wrapper>
        </Center>
      </body>
    </html>
  );
}
