import "../../globals.css";
import { GeistSans } from "geist/font/sans";
import Center from "@/components/Center";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import NextTopLoader from "nextjs-toploader";
import Sidebar from "@/components/dashboard/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PNGKY | dashboard🖐️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-my-white dark:bg-my-black scroll-smooth",
          GeistSans.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Center>
            <NextTopLoader showSpinner={false} color="#ffc300" />
            <main className="w-full flex min-h-screen">
              <Sidebar />
              <div className="ml-[180px] w-full">{children}</div>
            </main>
          </Center>
        </ThemeProvider>
      </body>
    </html>
  );
}
